version: "3.7"

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    ports:
      - "9106:8080"
      - "9107:5000"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /home/dockerVolume/jenkins:/var/jenkins_home
