version: "3.1"

services:

  cAdvisor:
    image: google/cadvisor:latest
    container_name: cAdvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "9110:8080"
#    environment:
#      - PGID=1000
#      - PUID=1000
#      - TZ=Europe/Copenhagen
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
