version: "3.1"

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    privileged: true
    ports:
      - 9111:3000
    volumes:
      - /home/dockerVolume/grafana/:/var/lib/grafana
      - /home/dockerVolume/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - PGID=1000
      - PUID=1000
