version: "3.7"

services:
  portainer:
    image: <name>
    container_name: <name>
    restart: unless-stopped
    privileged: true
    ports:
      - 91<number>:<number>
    networks:
      - dockerNet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /home/dockerVolume<portainer/data>:<data>

networks:
  dockerNet:
    external: true
