version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    privileged: true
    ports:
      - "9106:9000"
    networks:
      - dockerNet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dockerVolume/portainer/data:/data



networks:
  dockerNet:
    external: true
