apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nginx-persistent-volumes-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
