apiVersion: v1
kind: PersistentVolume
metadata:
  name: majestic-nfs-persistent-volumes
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 191.168.1.8
    path: /mnt/3tb_hdd/k8s_cluster_storage
