version: '3.7'

services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: unless-stopped
    ports:
      - 9115:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - dockerNet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /home/dockerVolume/netData:/etc/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw



networks:
  dockerNet:
    external: true


