version: "3.7"

services:
  rancher:
    image:  rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    privileged: true
    ports:
      - "9120:80"
      - "9121:443"
    networks:
      - dockerNet
    environment:
      - PGID=1000
      - PUID=1000



networks:
  dockerNet:
    external: true


