version: '3.7'

services:
   watchtower:
     image: containrrr/watchtower
     container_name: watchtower
     networks:
       - dockerNet
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
     restart: always



networks:
  dockerNet:
    external: true
